const markets = [
  {s:'BTC',q:'USDT',name:'Bitcoin',price:'67,892.11',usd:'$67,892.11',vol:'1.23B',chg:2.45,c:'btc',lev:'10x'},
  {s:'ETH',q:'USDT',name:'Ethereum',price:'3,245.67',usd:'$3,245.67',vol:'756.21M',chg:1.12,c:'eth',lev:'10x'},
  {s:'USDT',q:'USDC',name:'Tether',price:'0.9998',usd:'$0.99',vol:'502.13M',chg:-0.01,c:'usdt',lev:'5x'},
  {s:'BNB',q:'USDT',name:'BNB',price:'598.45',usd:'$598.45',vol:'256.55M',chg:3.21,c:'bnb',lev:'10x'},
  {s:'SOL',q:'USDT',name:'Solana',price:'185.35',usd:'$185.35',vol:'198.45M',chg:2.14,c:'sol',lev:'10x'},
  {s:'XRP',q:'USDT',name:'XRP',price:'0.5287',usd:'$0.52',vol:'178.32M',chg:.89,c:'xrp',lev:'10x'},
  {s:'DOGE',q:'USDT',name:'Dogecoin',price:'0.12456',usd:'$0.12',vol:'142.67M',chg:4.56,c:'doge',lev:'10x'},
  {s:'ADA',q:'USDT',name:'Cardano',price:'0.4657',usd:'$0.46',vol:'98.21M',chg:1.76,c:'ada',lev:'10x'}
];
let favorites = new Set(['BTC','ETH','SOL']);
let state={route:'home',marketTab:'Hot',quote:'All',orderSide:'buy'};
const page=document.getElementById('page');

function brandMobile(){return `<div class="brand-mobile mobile-only"><button class="brand" data-route="home"><span class="brand-word">COINL<span class="brand-loop">∞</span>K</span><span class="brand-global">GLOBAL</span></button><div class="actions"><button class="icon-btn" id="mSearch">⌕</button><button class="icon-btn" id="mNotify">♢<span class="dot"></span></button><button class="avatar" data-route="profile">●</button></div></div>`}
function spark(up=true){return `<svg class="spark" viewBox="0 0 120 36" preserveAspectRatio="none"><polyline fill="none" stroke="${up?'#00e28a':'#d1152f'}" stroke-width="2.2" points="0,30 10,24 18,27 28,16 38,19 48,13 58,20 68,10 78,14 88,7 98,12 108,5 120,8"/></svg>`}
function row(m,showVol=false){return `<div class="market-row" data-symbol="${m.s}"><div class="pair"><button class="star ${favorites.has(m.s)?'on':''}" data-fav="${m.s}">☆</button><span class="token ${m.c}">${m.s==='BTC'?'₿':m.s==='ETH'?'◆':m.s==='USDT'?'₮':m.s==='BNB'?'◇':m.s==='SOL'?'≋':m.s==='XRP'?'X':m.s==='DOGE'?'Ð':m.s==='ADA'?'A':'•'}</span><div><div><span class="symbol">${m.s}</span><span class="quote"> / ${m.q}</span><span class="lev">${m.lev}</span></div><div class="sub">${showVol?m.vol:''}</div></div></div><div><div class="symbol">${m.price}</div><div class="sub">${m.usd}</div></div><div class="spark-col">${spark(m.chg>=0)}</div><div class="change ${m.chg>=0?'up':'down'}">${m.chg>=0?'+':''}${m.chg.toFixed(2)}%</div></div>`}
function marketCard(limit=5){return `<section class="market-card"><div class="tabs">${['Favorites','Hot','Gainers','Losers','New'].map(t=>`<button class="tab ${state.marketTab===t?'active':''}" data-tab="${t}">${t}</button>`).join('')}</div><div class="market-head"><span>Pair</span><span>Last Price</span><span class="spark-col"></span><span style="text-align:right">24H Change</span></div><div id="marketRows">${getFiltered().slice(0,limit).map(m=>row(m)).join('')}</div><button class="view-more" data-route="markets">View More →</button></section>`}
function getFiltered(){let arr=[...markets];if(state.marketTab==='Favorites')arr=arr.filter(m=>favorites.has(m.s));if(state.marketTab==='Gainers')arr=arr.filter(m=>m.chg>0).sort((a,b)=>b.chg-a.chg);if(state.marketTab==='Losers')arr=arr.filter(m=>m.chg<0);if(state.marketTab==='New')arr=arr.slice().reverse();if(state.quote!=='All')arr=arr.filter(m=>m.q===state.quote||m.s===state.quote);return arr}
function home(){return `<div class="page home-page">${brandMobile()}<div class="desktop-only hero"><section class="hero-card"><h1>Trade <span class="accent">Crypto.</span><br>Anywhere. Anytime.</h1><p>Buy, sell & trade cryptocurrencies with a clean, fast and security-first experience.</p><div style="display:flex;gap:12px;margin-top:28px"><button class="btn primary" data-route="trade">Get Started</button><button class="btn ghost" data-route="markets">View Markets</button></div></section><section class="hero-art"><div class="hero-phone"><div class="loop">∞</div></div><div class="coin btc">₿</div><div class="coin eth">◆</div><div class="coin usdt">₮</div></section></div><section class="home-mobile-hero mobile-only"><h1>Trade <span class="accent">Crypto.</span><br>Anywhere. Anytime.</h1><p>Secure, fast & reliable crypto trading platform.</p><button class="btn primary" data-route="trade">Trade Now →</button><div class="mini-loop">∞</div></section>${quick()}<section class="invite"><div><strong>Invite Friends, Earn Together</strong><p>Get up to <span class="accent">30%</span> commission</p></div><button class="btn primary" id="inviteBtn">Invite Now →</button></section>${marketCard(5)}<div class="security-strip"><div class="sec-left"><span class="shield">⬡</span><div><b>Secure Your Assets</b><div class="sub">Enable 2FA for extra security</div></div></div><button class="btn ghost" id="twofaBtn">Enable Now →</button></div></div>`}
function quick(){let q=[['⇩','Deposit','assets'],['▥','Markets','markets'],['⇄','Trade','trade'],['S','Futures','futures'],['▣','Earn','earn'],['▦','More','more']];return `<div class="quick-grid">${q.map(x=>`<button class="quick" data-route="${x[2]}"><span class="qico">${x[0]}</span>${x[1]}</button>`).join('')}</div>`}
function marketsPage(){return `<div class="page">${brandMobile()}<div class="section-title"><h2>Markets</h2><button class="btn ghost" id="filterBtn">Filter</button></div><div class="filters">${['All','USDT','USDC','BTC','ETH'].map(q=>`<button class="chip ${state.quote===q?'active':''}" data-quote="${q}">${q}</button>`).join('')}</div><div class="market-layout"><section class="market-card"><div class="tabs">${['Favorites','Spot','Futures'].map((t,i)=>`<button class="tab ${i===0?'active':''}">${t}</button>`).join('')}</div><div class="market-head"><span>Pair / Vol</span><span>Last Price</span><span class="spark-col"></span><span style="text-align:right">24h Change</span></div><div>${getFiltered().map(m=>row(m,true)).join('')}</div></section><aside class="panel side-card"><h3>Market Search</h3><input id="marketSearch" class="input" placeholder="Search BTC, ETH..."/><p class="sub">Click any pair to open the trading screen.</p></aside></div></div>`}
function tradePage(futures=false){let m=markets[0];return `<div class="page">${brandMobile()}<div class="section-title"><h2>${futures?'Futures':'Spot'} Trading</h2><div class="positive">BTC/USDT</div></div><div class="trade-layout"><section class="panel chart-card"><div class="price-line"><span class="price-big">${m.price}</span><span class="positive">+2.45%</span></div><div class="sub">BTC/USDT · 24h High 68,952.31 · 24h Low 66,210.45</div><svg class="chart-svg" viewBox="0 0 800 300" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#00e28a" stop-opacity=".32"/><stop offset="1" stop-color="#00e28a" stop-opacity="0"/></linearGradient></defs><path d="M0 250 C80 230 100 180 160 200 S260 130 320 160 S410 100 480 120 S600 60 680 80 S750 30 800 38 L800 300 L0 300Z" fill="url(#g)"/><path d="M0 250 C80 230 100 180 160 200 S260 130 320 160 S410 100 480 120 S600 60 680 80 S750 30 800 38" fill="none" stroke="#00e28a" stroke-width="3"/></svg><div class="orderbook"><h3>Order Book</h3>${Array.from({length:8},(_,i)=>`<div class="ob-row"><span class="${i<4?'positive':''}">${(67892.11+(i-4)*12.4).toFixed(2)}</span><span>${(0.03+i*.011).toFixed(4)}</span><span>${(2400+i*955).toFixed(2)}</span></div>`).join('')}</div></section><aside class="panel order-card"><div class="seg"><button class="${state.orderSide==='buy'?'active buy':''}" data-side="buy">Buy</button><button class="${state.orderSide==='sell'?'active sell':''}" data-side="sell">Sell</button></div><div class="field"><label>Price (USDT)</label><input class="input" id="orderPrice" value="67892.11"></div><div class="field"><label>Amount (BTC)</label><input class="input" id="orderAmount" placeholder="0.0000"></div><div class="field"><label>Total (USDT)</label><input class="input" id="orderTotal" placeholder="0.00" readonly></div><div class="balance-line"><span>Available</span><span>39.20 USDT</span></div><button class="btn ${state.orderSide==='buy'?'primary':'ghost'} wide" id="placeOrder">${state.orderSide==='buy'?'Buy':'Sell'} BTC</button><p class="sub" style="margin-top:14px">Demo frontend: live order placement will be connected to your exchange backend API.</p></aside></div></div>`}
function assetsPage(){return `<div class="page">${brandMobile()}<section class="asset-hero desktop-only"><div><div class="sub">Est. total value</div><div class="asset-value">39.2 <span style="font-size:20px">USD</span></div><div>Today's PnL <span class="positive">+$0.06 (+0.16%)</span></div><button class="btn primary" id="depositBtn" style="margin-top:20px">Deposit</button></div><div class="loop-watermark">∞</div></section><section class="mobile-balance mobile-only"><div class="sub">Est. total value ◉</div><div class="asset-value">39.2 <span style="font-size:18px">USD</span></div><div>Today's PnL <span class="positive">+$0.06 (+0.16%)</span></div><div class="loop-watermark">∞</div><button class="btn primary" id="depositBtnM" style="margin-top:18px">Deposit</button></section>${quick()}<div class="asset-grid">${[['USDT','28.45'],['BTC','0.00011'],['ETH','0.0019'],['USDC','3.10']].map(a=>`<div class="panel asset-card"><div class="sub">${a[0]}</div><div style="font-size:22px;font-weight:800;margin-top:7px">${a[1]}</div><button class="btn ghost" style="margin-top:14px">Transfer</button></div>`).join('')}</div></div>`}
function profilePage(){return `<div class="page profile-wrap"><div class="profile-mobile-header mobile-only"><button class="mobile-back" data-route="home">‹</button><span class="mobile-globe">◎</span></div><section class="panel profile-card"><div class="profile-icon">◒</div><div><h2 style="margin:0">mk****@gmail.com</h2><div class="sub" style="font-size:16px;margin-top:8px">UID: LBA1C47754 ⧉</div><span class="verified">♢ Verified</span></div><div class="loop-watermark desktop-only" style="margin-left:auto;font-size:76px">∞</div></section>${menu(['Referral','Security','Preference'])}${menu(['Support Center','Official Channel','API Settings','About Coinlook'])}</div>`}
function menu(items){let ico={'Referral':'♧','Security':'⬡','Preference':'⬢','Support Center':'?','Official Channel':'▤','API Settings':'</>','About Coinlook':'ⓘ'};return `<section class="panel menu-group">${items.map(x=>`<div class="menu-row" data-menu="${x}"><div class="menu-left"><span class="menu-ico">${ico[x]}</span><b>${x}</b></div><span class="sub">${x==='About Coinlook'?'1.0.0  ›':'›'}</span></div>`).join('')}</section>`}
function generic(title,body){return `<div class="page">${brandMobile()}<section class="panel" style="padding:28px"><h2>${title}</h2><p style="color:#aeb6bc;line-height:1.7">${body}</p><button class="btn primary" data-route="home">Back Home</button></section></div>`}
function render(){document.querySelectorAll('[data-route]').forEach(()=>{});let html='';if(state.route==='home')html=home();else if(state.route==='markets')html=marketsPage();else if(state.route==='trade')html=tradePage(false);else if(state.route==='futures')html=tradePage(true);else if(state.route==='assets')html=assetsPage();else if(state.route==='profile')html=profilePage();else if(state.route==='earn')html=generic('Earn','Staking, flexible savings and campaign products can be connected here.');else html=generic('More','Referral, announcements, support, API settings and additional services can live here.');page.innerHTML=html;bind();updateNav()}
function updateNav(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));document.querySelectorAll('.topnav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route))}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;render();scrollTo(0,0)});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.marketTab=b.dataset.tab;render()});document.querySelectorAll('[data-quote]').forEach(b=>b.onclick=()=>{state.quote=b.dataset.quote;render()});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=(e)=>{e.stopPropagation();favorites.has(b.dataset.fav)?favorites.delete(b.dataset.fav):favorites.add(b.dataset.fav);render()});document.querySelectorAll('.market-row').forEach(r=>r.onclick=()=>{state.route='trade';render();scrollTo(0,0)});document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{state.orderSide=b.dataset.side;render()});let a=document.getElementById('orderAmount'),p=document.getElementById('orderPrice'),t=document.getElementById('orderTotal');if(a&&p&&t){const calc=()=>t.value=((parseFloat(a.value)||0)*(parseFloat(p.value)||0)).toFixed(2);a.oninput=calc;p.oninput=calc}const po=document.getElementById('placeOrder');if(po)po.onclick=()=>showModal(`<h2>Demo Order</h2><p>Your ${state.orderSide.toUpperCase()} order UI is working. Connect the backend trading API to submit a real order.</p><button class="btn primary wide" onclick="hideModal()">Done</button>`);['inviteBtn','twofaBtn','depositBtn','depositBtnM','loginBtn','signupBtn','searchBtn','notifyBtn','mSearch','mNotify','filterBtn'].forEach(id=>{let el=document.getElementById(id);if(el)el.onclick=()=>handleAction(id)});document.querySelectorAll('[data-menu]').forEach(x=>x.onclick=()=>showModal(`<h2>${x.dataset.menu}</h2><p>This screen is wired and ready for its backend/API implementation.</p><button class="btn primary wide" onclick="hideModal()">Close</button>`));let s=document.getElementById('marketSearch');if(s)s.oninput=()=>{let q=s.value.toUpperCase();document.querySelectorAll('.market-row').forEach(r=>r.style.display=r.dataset.symbol.includes(q)?'grid':'none')}}
function handleAction(id){let title=id.toLowerCase().includes('deposit')?'Deposit':id.toLowerCase().includes('twofa')?'Two-Factor Authentication':id.toLowerCase().includes('invite')?'Referral Invite':id.toLowerCase().includes('signup')?'Create Account':id.toLowerCase().includes('login')?'Log In':'Search & Notifications';showModal(`<h2>${title}</h2><p>The frontend interaction is working. This action will call your secure backend when the API is connected.</p>${title==='Deposit'?'<select class="input"><option>USDT</option><option>BTC</option><option>ETH</option></select><button class="btn primary wide" style="margin-top:12px">Generate Deposit Address</button>':''}`)}
function showModal(x){document.getElementById('modalBody').innerHTML=x;document.getElementById('modal').classList.remove('hidden')}window.hideModal=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('modalClose').onclick=hideModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')hideModal()};render();
